; generated by OrcaSlicer 2.3.0 on 2025-06-05 at 23:51:17

; ELEGOO_Z205_PLA.gcode for ELEGOO CENTAURI CARBON (Z-bed positioning)
; For OTTOMAT3D automation - Starts a full print job that finishes with Z Position at 205mm. 
; NOTE: THIS PARTICULAR FILE WILL NOT WORK AS MOST OF THE GCODE HAS BEEN DELETED FOR VIEWING PURPOSES. 


; EXECUTABLE_BLOCK_START
G90
G28 ;home
M729 ;Clean Nozzle


; filament end gcode
;===== date: 20250109 =====================
M400 ; wait for buffer to clear
M140 S0 ;Turn-off bed
M106 S255 ;Cooling nozzle
M83
G92 E0 ; zero the extruder
G2 I1 J0 Z3.1 E-1 F3000 ; lower z a little
G90
G1 Z100 F20000 ; Move print head up 
M204 S5000
M400
M83
G1 X202 F20000
M400
G1 Y250 F20000
G1 Y264.5 F1200
M400
G92 E0
M104 S0 ;Turn-off hotend
M140 S0 ;Turn-off bed
M106 S0 ; turn off fan
M106 P2 S0 ; turn off remote part cooling fan
M106 P3 S0 ; turn off chamber cooling fan
G1 Z205;
M84 ;Disable all steppers
; EXECUTABLE_BLOCK_END




