; generated by PrusaSlicer 2.9.2 on 2025-05-26 at 02:08:47 UTC
; Removed Thumbnails and irrelelevant information to minimise redundancy. 

; Y_POS_DWELL.gcode for MK-4 (Y-bed positioning)
; For OTTOMAT3D automation - moves Y to 210mm and dwells

M73 P0 R1
M73 C0
M73 Q0 S1
M73 D0
M201 X4000 Y4000 Z200 E2500 ; sets maximum accelerations, mm/sec^2
M203 X300 Y300 Z40 E100 ; sets maximum feedrates, mm / sec
M204 P4000 R1200 T4000 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z2.00 E10.00 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M85 S3600
M486 S0
M486 AEmbossed text
M486 S-1

;TYPE:Custom
M17 ; enable steppers
M862.1 P0.4 A0 F0 ; nozzle check
M862.3 P "MK4" ; printer model check
M862.5 P2 ; g-code level check
M862.6 P"Input shaper" ; FW feature check
M115 U6.2.4+8909

M555 X105.364 Y96.2931 W39.2729 H13.4136

G90 ; use absolute coordinates
M83 ; extruder relative mode

; M140 S60 ; set bed temp
; M104 T0 S170 ; set extruder temp for bed leveling
; M109 T0 R170 ; wait for temp

M84 E ; turn off E motor

G28 Y0; home all without mesh bed level

G1 Y210 F2400

M84 S600 X Y E

G4 S3600


;PAUSE_PRINT
M117 WAITING FOR EJECTION
; M601

